import type { LabTemplate, PhotoClassConfig } from "./inputs";

export const photoClassConfigs: PhotoClassConfig[] = [
  {
    className: "Grape___Black_rot",
    crop: "grape",
    expectedDiagnosis: "Grape black rot",
    expectedConditionType: "disease",
    symptoms: "tan leaf spots with black fruiting bodies and early berry rot",
    descriptionTemplate:
      "Tan circular spots with black fruiting bodies are visible on leaves; a few berries show early rot.",
    mustInclude: ["remove mummies", "fungicide timing", "canopy airflow"],
    shouldAvoid: ["ignore fruit infection"],
    season: "bloom to fruit set",
    location: "Finger Lakes, NY",
  },
  {
    className: "Grape___Esca_(Black_Measles)",
    crop: "grape",
    expectedDiagnosis: "Esca (black measles)",
    expectedConditionType: "disease",
    symptoms: "tiger-stripe chlorosis and necrosis between veins",
    descriptionTemplate:
      "Leaves show tiger-stripe patterns with interveinal necrosis; symptoms are scattered across older vines.",
    mustInclude: ["trunk disease management", "avoid trunk injury", "rogue infected vines"],
    shouldAvoid: ["curative fungicide claim"],
    season: "mid-summer",
    location: "Napa Valley, CA",
  },
  {
    className: "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    crop: "grape",
    expectedDiagnosis: "Grape leaf blight",
    expectedConditionType: "disease",
    symptoms: "irregular brown lesions with yellow halos on older leaves",
    descriptionTemplate:
      "Irregular brown lesions with yellow halos are spreading on lower leaves in a dense canopy.",
    mustInclude: ["canopy airflow", "fungicide rotation", "sanitation"],
    shouldAvoid: ["late rescue spray"],
    season: "early summer",
    location: "Lake Erie, PA",
  },
  {
    className: "Tomato___Bacterial_spot",
    crop: "tomato",
    expectedDiagnosis: "Bacterial spot",
    expectedConditionType: "disease",
    symptoms: "dark lesions with yellow halos on leaves and fruit in warm wet weather",
    descriptionTemplate:
      "Dark, greasy lesions with yellow halos appear on leaves and green fruit after warm, wet weather.",
    mustInclude: ["sanitation", "copper+bactericide caution", "avoid overhead irrigation"],
    shouldAvoid: ["late curative claim"],
    season: "early fruiting",
    location: "Leamington, ON",
  },
  {
    className: "Tomato___Septoria_leaf_spot",
    crop: "tomato",
    expectedDiagnosis: "Septoria leaf spot",
    expectedConditionType: "disease",
    symptoms: "small circular spots with dark borders and gray centers",
    descriptionTemplate:
      "Small circular spots with dark borders and gray centers are expanding on lower leaves.",
    mustInclude: ["sanitation", "fungicide rotation", "avoid overhead irrigation"],
    shouldAvoid: ["assume nutrient deficiency only"],
    season: "mid-season",
    location: "Chilliwack, BC",
  },
  {
    className: "Tomato___Late_blight",
    crop: "tomato",
    expectedDiagnosis: "Late blight",
    expectedConditionType: "disease",
    symptoms: "water-soaked lesions with rapid blighting in cool wet weather",
    descriptionTemplate:
      "Water-soaked lesions with rapid blighting appear after cool, wet conditions; white growth is visible on undersides.",
    mustInclude: ["urgent removal", "protectant fungicide timing", "destroy cull piles"],
    shouldAvoid: ["wait and see"],
    season: "mid-season",
    location: "Fraser Valley, BC",
  },
];

export const labTemplates: LabTemplate[] = [
  {
    name: "soybean_frogeye_leaf_spot",
    crop: "soybean",
    season: "R2-R4",
    locations: ["Boone County, IA", "Shelby County, MO"],
    symptoms: "circular gray lesions with reddish-purple margins after humid weather",
    expectedDiagnosis: "Frogeye leaf spot",
    expectedConditionType: "disease",
    mustInclude: ["variety resistance", "fungicide timing", "scout severity"],
    shouldAvoid: ["nutrient-only explanation"],
    labData: {
      ph: 6.4,
      soilPh: 6.4,
      organicMatter: 3.0,
      nitrogen: 12,
      phosphorus: 20,
      potassium: 145,
      calcium: 1600,
      magnesium: 210,
      sulfur: 12,
      zinc: 0.8,
      manganese: 10,
      iron: 35,
      copper: 0.4,
      boron: 0.4,
      cec: 18,
      baseSaturation: 72,
    },
    labName: "Midwest Plant Lab",
  },
  {
    name: "soybean_phytophthora_root_rot",
    crop: "soybean",
    season: "V3-V5",
    locations: ["Clay County, SD", "Cass County, ND"],
    symptoms: "wilting with brown stem lesions at soil line in low wet areas",
    expectedDiagnosis: "Phytophthora root rot",
    expectedConditionType: "disease",
    mustInclude: ["resistant variety", "drainage improvement", "seed treatment"],
    shouldAvoid: ["foliar fungicide only"],
    labData: {
      ph: 6.8,
      soilPh: 6.8,
      organicMatter: 4.2,
      nitrogen: 14,
      phosphorus: 22,
      potassium: 130,
      calcium: 1750,
      magnesium: 240,
      sulfur: 10,
      zinc: 0.6,
      manganese: 8,
      iron: 30,
      copper: 0.3,
      boron: 0.3,
      cec: 20,
      baseSaturation: 76,
    },
    labName: "Prairie Diagnostics",
  },
  {
    name: "tomato_bacterial_canker",
    crop: "tomato",
    season: "fruit set",
    locations: ["Leamington, ON", "Chilliwack, BC"],
    symptoms: "wilting on one side with bird's-eye lesions on fruit",
    expectedDiagnosis: "Bacterial canker",
    expectedConditionType: "disease",
    mustInclude: ["sanitation", "seed health", "copper program caution"],
    shouldAvoid: ["late curative claim"],
    labData: {
      ph: 6.5,
      soilPh: 6.5,
      organicMatter: 3.2,
      nitrogen: 18,
      phosphorus: 35,
      potassium: 200,
      calcium: 2200,
      magnesium: 320,
      sulfur: 15,
      zinc: 1.2,
      manganese: 12,
      iron: 40,
      copper: 0.6,
      boron: 0.5,
      cec: 22,
      baseSaturation: 78,
    },
    labName: "Ontario AgriLab",
  },
  {
    name: "tomato_bacterial_speck",
    crop: "tomato",
    season: "early fruiting",
    locations: ["Norfolk County, ON", "Fraser Valley, BC"],
    symptoms: "tiny dark specks with yellow halos on leaves and fruit after cool wet weather",
    expectedDiagnosis: "Bacterial speck",
    expectedConditionType: "disease",
    mustInclude: ["weather-based risk", "sanitation", "copper resistance caution"],
    shouldAvoid: ["nitrogen-only fix"],
    labData: {
      ph: 6.3,
      soilPh: 6.3,
      organicMatter: 2.8,
      nitrogen: 16,
      phosphorus: 28,
      potassium: 180,
      calcium: 2100,
      magnesium: 290,
      sulfur: 14,
      zinc: 1.0,
      manganese: 11,
      iron: 38,
      copper: 0.5,
      boron: 0.4,
      cec: 19,
      baseSaturation: 75,
    },
    labName: "BC AgriService Lab",
  },
  {
    name: "grape_magnesium_deficiency",
    crop: "grape",
    season: "veraison",
    locations: ["Niagara, ON", "Finger Lakes, NY"],
    symptoms: "interveinal chlorosis on older leaves with marginal necrosis",
    expectedDiagnosis: "Magnesium deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["magnesium source", "potassium antagonism", "soil test follow-up"],
    shouldAvoid: ["fungicide only"],
    labData: {
      ph: 6.7,
      soilPh: 6.7,
      organicMatter: 2.2,
      nitrogen: 10,
      phosphorus: 18,
      potassium: 190,
      calcium: 2200,
      magnesium: 70,
      sulfur: 10,
      zinc: 0.6,
      manganese: 5,
      iron: 15,
      copper: 0.2,
      boron: 0.3,
      cec: 14,
      baseSaturation: 68,
    },
    labName: "Vineyard Analytics",
  },
  {
    name: "grape_potassium_deficiency",
    crop: "grape",
    season: "pre-veraison",
    locations: ["Napa Valley, CA", "Okanagan Valley, BC"],
    symptoms: "marginal scorch and weak shoot growth with low juice brix",
    expectedDiagnosis: "Potassium deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["petiole test", "potassium source", "timing before veraison"],
    shouldAvoid: ["late heavy potassium at ripening"],
    labData: {
      ph: 7.2,
      soilPh: 7.2,
      organicMatter: 1.9,
      nitrogen: 8,
      phosphorus: 14,
      potassium: 60,
      calcium: 2400,
      magnesium: 180,
      sulfur: 8,
      zinc: 0.5,
      manganese: 4,
      iron: 12,
      copper: 0.2,
      boron: 0.3,
      cec: 13,
      baseSaturation: 70,
    },
    labName: "West Coast Vit Lab",
  },
  {
    name: "sorghum_n_deficiency",
    crop: "sorghum",
    season: "V4-V6",
    locations: ["Reno County, KS", "Donley County, TX"],
    symptoms: "pale green leaves and lower leaf yellowing with thin stands",
    expectedDiagnosis: "Nitrogen deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["nitrogen rate", "split application", "rainfall incorporation"],
    shouldAvoid: ["late rescue claim"],
    labData: {
      ph: 6.1,
      soilPh: 6.1,
      organicMatter: 1.5,
      nitrogen: 5,
      phosphorus: 12,
      potassium: 95,
      calcium: 900,
      magnesium: 110,
      sulfur: 7,
      zinc: 0.4,
      manganese: 6,
      iron: 20,
      copper: 0.25,
      boron: 0.3,
      cec: 9,
      baseSaturation: 60,
    },
    labName: "KSU Soil Lab",
  },
  {
    name: "sorghum_zinc_deficiency",
    crop: "sorghum",
    season: "V3-V5",
    locations: ["Ellis County, KS", "Greer County, OK"],
    symptoms: "interveinal chlorosis and white bands on young leaves",
    expectedDiagnosis: "Zinc deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["zinc source", "soil pH note", "banded application"],
    shouldAvoid: ["ignoring high pH"],
    labData: {
      ph: 7.9,
      soilPh: 7.9,
      organicMatter: 1.3,
      nitrogen: 8,
      phosphorus: 16,
      potassium: 120,
      calcium: 2100,
      magnesium: 190,
      sulfur: 9,
      zinc: 0.2,
      manganese: 4,
      iron: 8,
      copper: 0.2,
      boron: 0.2,
      cec: 12,
      baseSaturation: 82,
    },
    labName: "Plains Soil Testing",
  },
];
