export type ConditionType =
  | "deficiency"
  | "disease"
  | "pest"
  | "environmental"
  | "unknown";

export interface PhotoClassConfig {
  className: string;
  crop: string;
  expectedDiagnosis: string;
  expectedConditionType: ConditionType;
  symptoms: string;
  descriptionTemplate: string;
  mustInclude: string[];
  shouldAvoid: string[];
  season: string;
  location: string;
}

export interface LabTemplate {
  name: string;
  crop: string;
  season: string;
  locations: string[];
  symptoms: string;
  expectedDiagnosis: string;
  expectedConditionType: ConditionType;
  mustInclude: string[];
  shouldAvoid: string[];
  labData: {
    ph: number;
    soilPh: number;
    organicMatter: number;
    nitrogen: number;
    phosphorus: number;
    potassium: number;
    calcium: number;
    magnesium: number;
    sulfur: number;
    zinc: number;
    manganese: number;
    iron: number;
    copper: number;
    boron: number;
    cec: number;
    baseSaturation: number;
  };
  labName: string;
}

export const photoClassConfigs: PhotoClassConfig[] = [
  {
    className: "Apple___Apple_scab",
    crop: "apple",
    expectedDiagnosis: "Apple scab",
    expectedConditionType: "disease",
    symptoms: "olive-green velvety lesions on leaves with some distortion",
    descriptionTemplate:
      "Leaf surfaces show olive-green, velvety lesions with mild curling. Spots are most dense in shaded areas after recent rain.",
    mustInclude: ["scouting", "fungicide timing", "sanitation"],
    shouldAvoid: ["late curative claim"],
    season: "tight cluster to petal fall",
    location: "Hudson Valley, NY",
  },
  {
    className: "Apple___Black_rot",
    crop: "apple",
    expectedDiagnosis: "Apple black rot",
    expectedConditionType: "disease",
    symptoms: "concentric ring lesions with purple margins on older leaves",
    descriptionTemplate:
      "Older leaves show circular lesions with concentric rings and a purple border. A few mummified fruits remain in the canopy.",
    mustInclude: ["remove mummified fruit", "fungicide rotation", "pruning airflow"],
    shouldAvoid: ["ignore fruit infection"],
    season: "early fruit set",
    location: "Yakima Valley, WA",
  },
  {
    className: "Apple___Cedar_apple_rust",
    crop: "apple",
    expectedDiagnosis: "Cedar apple rust",
    expectedConditionType: "disease",
    symptoms: "yellow-orange leaf spots with slight swelling",
    descriptionTemplate:
      "Bright yellow-orange spots with slight swelling appear on upper leaf surfaces. Symptoms appeared after a wet period.",
    mustInclude: ["nearby cedar hosts", "fungicide timing", "resistant varieties"],
    shouldAvoid: ["late-season cure"],
    season: "pink to petal fall",
    location: "Central PA",
  },
  {
    className: "Apple___healthy",
    crop: "apple",
    expectedDiagnosis: "No obvious disease; healthy foliage",
    expectedConditionType: "unknown",
    symptoms: "uniform green leaves with no lesions",
    descriptionTemplate:
      "Leaves are uniformly green with no visible lesions or distortion. Canopy looks balanced and vigorous.",
    mustInclude: ["continue monitoring", "baseline nutrition check"],
    shouldAvoid: ["unnecessary fungicide"],
    season: "early summer",
    location: "Wenatchee, WA",
  },
  {
    className: "Blueberry___healthy",
    crop: "blueberry",
    expectedDiagnosis: "No obvious disease; healthy foliage",
    expectedConditionType: "unknown",
    symptoms: "clean, glossy leaves and normal growth",
    descriptionTemplate:
      "Leaves are glossy, deep green, and show normal growth with no spotting or chlorosis.",
    mustInclude: ["monitor pest pressure", "maintain nutrition"],
    shouldAvoid: ["preventive sprays without risk"],
    season: "post-bloom",
    location: "Hammonton, NJ",
  },
  {
    className: "Cherry_(including_sour)___Powdery_mildew",
    crop: "cherry",
    expectedDiagnosis: "Powdery mildew",
    expectedConditionType: "disease",
    symptoms: "white powdery growth on leaf surfaces with curling",
    descriptionTemplate:
      "White powdery patches appear on young leaves, with slight curling and reduced vigor.",
    mustInclude: ["canopy airflow", "fungicide threshold", "avoid evening irrigation"],
    shouldAvoid: ["high-rate sulfur in heat"],
    season: "late spring",
    location: "Traverse City, MI",
  },
  {
    className: "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    crop: "corn",
    expectedDiagnosis: "Gray leaf spot",
    expectedConditionType: "disease",
    symptoms: "rectangular gray lesions bounded by veins",
    descriptionTemplate:
      "Rectangular gray lesions bounded by veins are visible on mid-canopy leaves after humid weather.",
    mustInclude: ["hybrid resistance", "fungicide timing", "residue management"],
    shouldAvoid: ["single chemistry reliance"],
    season: "V8 to VT",
    location: "Central IL",
  },
  {
    className: "Corn_(maize)___Common_rust_",
    crop: "corn",
    expectedDiagnosis: "Common rust",
    expectedConditionType: "disease",
    symptoms: "cinnamon-brown pustules scattered on leaves",
    descriptionTemplate:
      "Scattered cinnamon-brown pustules appear on leaves; severity is moderate in low-lying areas.",
    mustInclude: ["scouting thresholds", "hybrid resistance", "fungicide if severe"],
    shouldAvoid: ["panic spray without threshold"],
    season: "V6 to V10",
    location: "Southwest IA",
  },
  {
    className: "Corn_(maize)___Northern_Leaf_Blight",
    crop: "corn",
    expectedDiagnosis: "Northern corn leaf blight",
    expectedConditionType: "disease",
    symptoms: "long cigar-shaped lesions on leaves",
    descriptionTemplate:
      "Long, cigar-shaped gray-green lesions are expanding on lower leaves after a cool, wet stretch.",
    mustInclude: ["fungicide timing", "residue management", "hybrid resistance"],
    shouldAvoid: ["late curative claim"],
    season: "V8 to R1",
    location: "Southeast MN",
  },
  {
    className: "Corn_(maize)___healthy",
    crop: "corn",
    expectedDiagnosis: "No obvious disease; healthy foliage",
    expectedConditionType: "unknown",
    symptoms: "even green color and intact leaf tissue",
    descriptionTemplate:
      "Leaves are even green with no visible lesions or chlorosis; overall crop looks healthy.",
    mustInclude: ["continue monitoring", "maintain fertility plan"],
    shouldAvoid: ["unneeded fungicide"],
    season: "V5 to V7",
    location: "North-central IN",
  },
  {
    className: "Grape___Black_rot",
    crop: "grape",
    expectedDiagnosis: "Grape black rot",
    expectedConditionType: "disease",
    symptoms: "tan leaf spots with black fruiting bodies",
    descriptionTemplate:
      "Tan circular spots with black fruiting bodies are present on leaves; some berries show early rot.",
    mustInclude: ["remove mummies", "fungicide timing", "canopy management"],
    shouldAvoid: ["ignore fruit infection"],
    season: "bloom to fruit set",
    location: "Finger Lakes, NY",
  },
  {
    className: "Grape___Esca_(Black_Measles)",
    crop: "grape",
    expectedDiagnosis: "Esca (black measles)",
    expectedConditionType: "disease",
    symptoms: "tiger-stripe chlorosis and necrosis between veins",
    descriptionTemplate:
      "Leaves show tiger-stripe patterns with interveinal necrosis; symptoms are patchy across the block.",
    mustInclude: ["remove infected vines", "trunk disease management", "avoid trunk injury"],
    shouldAvoid: ["curative fungicide claim"],
    season: "mid-summer",
    location: "Napa Valley, CA",
  },
  {
    className: "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    crop: "grape",
    expectedDiagnosis: "Grape leaf blight",
    expectedConditionType: "disease",
    symptoms: "irregular brown lesions with yellow halos",
    descriptionTemplate:
      "Irregular brown lesions with yellow halos are spreading on lower leaves in a dense canopy.",
    mustInclude: ["fungicide rotation", "canopy airflow", "sanitation"],
    shouldAvoid: ["late rescue spray"],
    season: "early summer",
    location: "Lake Erie, PA",
  },
  {
    className: "Orange___Haunglongbing_(Citrus_greening)",
    crop: "citrus",
    expectedDiagnosis: "Citrus greening (HLB)",
    expectedConditionType: "disease",
    symptoms: "blotchy mottle and yellow shoots",
    descriptionTemplate:
      "Leaves show blotchy, asymmetric mottling with yellow shoots and stunted new flush.",
    mustInclude: ["psyllid management", "confirmatory testing", "rouging infected trees"],
    shouldAvoid: ["foliar nutrition cure"],
    season: "year-round",
    location: "Central FL",
  },
  {
    className: "Peach___Bacterial_spot",
    crop: "peach",
    expectedDiagnosis: "Peach bacterial spot",
    expectedConditionType: "disease",
    symptoms: "angular leaf spots and shot-hole appearance",
    descriptionTemplate:
      "Leaves show angular spots that drop out, creating a shot-hole appearance; some fruit show pitting.",
    mustInclude: ["copper sprays timing", "resistant varieties", "avoid overhead irrigation"],
    shouldAvoid: ["late curative spray"],
    season: "early summer",
    location: "South GA",
  },
  {
    className: "Pepper,_bell___Bacterial_spot",
    crop: "bell pepper",
    expectedDiagnosis: "Bacterial spot",
    expectedConditionType: "disease",
    symptoms: "water-soaked lesions with yellow halos",
    descriptionTemplate:
      "Water-soaked lesions with yellow halos are visible on leaves; some defoliation is starting.",
    mustInclude: ["seed sanitation", "copper plus protectant", "avoid working wet fields"],
    shouldAvoid: ["overhead irrigation during outbreaks"],
    season: "mid-summer",
    location: "Immokalee, FL",
  },
  {
    className: "Potato___Early_blight",
    crop: "potato",
    expectedDiagnosis: "Early blight",
    expectedConditionType: "disease",
    symptoms: "concentric rings on lower leaves",
    descriptionTemplate:
      "Lower leaves show concentric rings with chlorotic halos; symptoms are moving upward.",
    mustInclude: ["fungicide timing", "nutrient balance", "irrigation management"],
    shouldAvoid: ["late curative claim"],
    season: "tuber initiation",
    location: "Red River Valley, ND",
  },
  {
    className: "Potato___Late_blight",
    crop: "potato",
    expectedDiagnosis: "Late blight",
    expectedConditionType: "disease",
    symptoms: "water-soaked lesions with white sporulation",
    descriptionTemplate:
      "Water-soaked lesions with white sporulation on leaf undersides appear after cool, wet nights.",
    mustInclude: ["immediate fungicide program", "destroy volunteers", "late blight alerts"],
    shouldAvoid: ["delay action"],
    season: "early bulking",
    location: "Aroostook County, ME",
  },
  {
    className: "Squash___Powdery_mildew",
    crop: "squash",
    expectedDiagnosis: "Powdery mildew",
    expectedConditionType: "disease",
    symptoms: "white powder on leaf surfaces",
    descriptionTemplate:
      "White powdery growth is spreading across older leaves; canopy is dense and humid.",
    mustInclude: ["fungicide rotation", "resistant varieties", "scouting"],
    shouldAvoid: ["late-season rescue"],
    season: "fruiting",
    location: "Eastern NC",
  },
  {
    className: "Strawberry___Leaf_scorch",
    crop: "strawberry",
    expectedDiagnosis: "Leaf scorch",
    expectedConditionType: "disease",
    symptoms: "purple to dark spots with scorched leaf margins",
    descriptionTemplate:
      "Leaves show purple to dark spots that coalesce, with scorched margins in older foliage.",
    mustInclude: ["renovation", "fungicide if needed", "remove old leaves"],
    shouldAvoid: ["ignore disease carryover"],
    season: "post-harvest",
    location: "Watsonville, CA",
  },
  {
    className: "Tomato___Bacterial_spot",
    crop: "tomato",
    expectedDiagnosis: "Bacterial spot",
    expectedConditionType: "disease",
    symptoms: "small dark lesions with yellow halos",
    descriptionTemplate:
      "Small dark lesions with yellow halos are present on lower leaves; some lesions appear on fruit.",
    mustInclude: ["seed sanitation", "copper sprays", "avoid overhead irrigation"],
    shouldAvoid: ["late curative spray"],
    season: "early fruit set",
    location: "Fresno, CA",
  },
  {
    className: "Tomato___Early_blight",
    crop: "tomato",
    expectedDiagnosis: "Early blight",
    expectedConditionType: "disease",
    symptoms: "target-like lesions on older leaves",
    descriptionTemplate:
      "Older leaves show target-like lesions with yellowing between veins; lower canopy is thinning.",
    mustInclude: ["mulch to reduce splash", "fungicide rotation", "remove lower leaves"],
    shouldAvoid: ["overreliance on single mode"],
    season: "mid-season",
    location: "Modesto, CA",
  },
  {
    className: "Tomato___Late_blight",
    crop: "tomato",
    expectedDiagnosis: "Late blight",
    expectedConditionType: "disease",
    symptoms: "water-soaked lesions and white growth on undersides",
    descriptionTemplate:
      "Water-soaked lesions are expanding rapidly; white sporulation is visible on leaf undersides after dew.",
    mustInclude: ["immediate fungicide", "destroy infected plants", "late blight alerts"],
    shouldAvoid: ["delay action"],
    season: "peak fruiting",
    location: "Western NY",
  },
  {
    className: "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    crop: "tomato",
    expectedDiagnosis: "Tomato yellow leaf curl virus",
    expectedConditionType: "disease",
    symptoms: "upward leaf curling, yellowing, and stunting",
    descriptionTemplate:
      "New growth is stunted with upward curling and yellowing; whiteflies are present on the underside.",
    mustInclude: ["whitefly control", "remove infected plants", "resistant varieties"],
    shouldAvoid: ["fungicide recommendations"],
    season: "early to mid-season",
    location: "South TX",
  },
  {
    className: "Soybean___healthy",
    crop: "soybean",
    expectedDiagnosis: "No obvious disease; healthy foliage",
    expectedConditionType: "unknown",
    symptoms: "uniform green trifoliates and healthy canopy",
    descriptionTemplate:
      "Trifoliates are uniform green with no visible lesions or chlorosis; stand is even.",
    mustInclude: ["continue monitoring", "maintain fertility plan"],
    shouldAvoid: ["unneeded fungicide"],
    season: "R1",
    location: "Central IA",
  },
];

export const labTemplates: LabTemplate[] = [
  {
    name: "corn_n_deficiency",
    crop: "corn",
    season: "V4-V6",
    locations: ["Boone County, IA", "McLean County, IL"],
    symptoms: "lower leaves yellowing with pale canopy after wet spring",
    expectedDiagnosis: "Nitrogen deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["soil or tissue test", "split nitrogen application", "timing by growth stage"],
    shouldAvoid: ["single high-rate burn risk advice"],
    labData: {
      ph: 6.2,
      soilPh: 6.2,
      organicMatter: 1.8,
      nitrogen: 6,
      phosphorus: 12,
      potassium: 95,
      calcium: 950,
      magnesium: 110,
      sulfur: 8,
      zinc: 0.6,
      manganese: 6,
      iron: 18,
      copper: 0.3,
      boron: 0.4,
      cec: 10,
      baseSaturation: 62,
    },
    labName: "AgriTech Labs",
  },
  {
    name: "corn_p_deficiency",
    crop: "corn",
    season: "V2-V4",
    locations: ["Story County, IA", "Tippecanoe County, IN"],
    symptoms: "purpling leaves and slow growth in cool wet soil",
    expectedDiagnosis: "Phosphorus deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["soil temperature context", "banded phosphorus", "starter timing"],
    shouldAvoid: ["blaming disease without evidence"],
    labData: {
      ph: 5.7,
      soilPh: 5.7,
      organicMatter: 2.4,
      nitrogen: 10,
      phosphorus: 5,
      potassium: 110,
      calcium: 820,
      magnesium: 95,
      sulfur: 9,
      zinc: 0.5,
      manganese: 7,
      iron: 20,
      copper: 0.3,
      boron: 0.3,
      cec: 9,
      baseSaturation: 58,
    },
    labName: "Midwest Soil Analytics",
  },
  {
    name: "soybean_k_deficiency",
    crop: "soybean",
    season: "R3-R5",
    locations: ["Champaign County, IL", "Hardin County, OH"],
    symptoms: "marginal chlorosis progressing to necrosis in upper canopy",
    expectedDiagnosis: "Potassium deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["rate by soil test", "timing guardrails", "check Mg antagonism"],
    shouldAvoid: ["ignoring Mg antagonism risk"],
    labData: {
      ph: 6.4,
      soilPh: 6.4,
      organicMatter: 2.2,
      nitrogen: 12,
      phosphorus: 16,
      potassium: 62,
      calcium: 1050,
      magnesium: 240,
      sulfur: 11,
      zinc: 0.7,
      manganese: 9,
      iron: 22,
      copper: 0.4,
      boron: 0.4,
      cec: 15,
      baseSaturation: 68,
    },
    labName: "AgSource Labs",
  },
  {
    name: "soybean_iron_chlorosis",
    crop: "soybean",
    season: "V2-V3",
    locations: ["Red River Valley, ND", "Clay County, MN"],
    symptoms: "interveinal chlorosis on young leaves with green veins",
    expectedDiagnosis: "Iron deficiency chlorosis",
    expectedConditionType: "deficiency",
    mustInclude: ["variety tolerance", "chelate guidance", "drainage note"],
    shouldAvoid: ["high confidence without differential"],
    labData: {
      ph: 7.8,
      soilPh: 7.8,
      organicMatter: 3.5,
      nitrogen: 14,
      phosphorus: 18,
      potassium: 135,
      calcium: 1850,
      magnesium: 280,
      sulfur: 12,
      zinc: 0.4,
      manganese: 4,
      iron: 3,
      copper: 0.2,
      boron: 0.3,
      cec: 22,
      baseSaturation: 78,
    },
    labName: "Prairie Analytics",
  },
  {
    name: "wheat_s_deficiency",
    crop: "wheat",
    season: "tillering",
    locations: ["Sedgwick County, KS", "Payne County, OK"],
    symptoms: "pale upper leaves and slow tiller growth",
    expectedDiagnosis: "Sulfur deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["sulfur source selection", "split application", "rainfall incorporation"],
    shouldAvoid: ["late-season rescue claim"],
    labData: {
      ph: 6.3,
      soilPh: 6.3,
      organicMatter: 1.6,
      nitrogen: 9,
      phosphorus: 14,
      potassium: 105,
      calcium: 980,
      magnesium: 120,
      sulfur: 4,
      zinc: 0.6,
      manganese: 6,
      iron: 19,
      copper: 0.3,
      boron: 0.3,
      cec: 11,
      baseSaturation: 60,
    },
    labName: "Great Plains Labs",
  },
  {
    name: "cotton_b_deficiency",
    crop: "cotton",
    season: "square to bloom",
    locations: ["Lubbock County, TX", "Cochran County, TX"],
    symptoms: "square shedding and short internodes",
    expectedDiagnosis: "Boron deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["boron rate guardrails", "tissue test", "avoid toxicity"],
    shouldAvoid: ["excess boron application"],
    labData: {
      ph: 7.1,
      soilPh: 7.1,
      organicMatter: 1.2,
      nitrogen: 10,
      phosphorus: 10,
      potassium: 85,
      calcium: 1250,
      magnesium: 140,
      sulfur: 7,
      zinc: 0.5,
      manganese: 5,
      iron: 14,
      copper: 0.2,
      boron: 0.2,
      cec: 9,
      baseSaturation: 64,
    },
    labName: "High Plains Soil Lab",
  },
  {
    name: "canola_b_deficiency",
    crop: "canola",
    season: "bolting",
    locations: ["Renville County, ND", "Saskatoon, SK"],
    symptoms: "hollow stems and poor flowering",
    expectedDiagnosis: "Boron deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["boron tissue test", "foliar vs soil", "rate guardrails"],
    shouldAvoid: ["blanket high-rate boron"],
    labData: {
      ph: 6.5,
      soilPh: 6.5,
      organicMatter: 2.1,
      nitrogen: 12,
      phosphorus: 13,
      potassium: 120,
      calcium: 1000,
      magnesium: 130,
      sulfur: 10,
      zinc: 0.6,
      manganese: 7,
      iron: 16,
      copper: 0.3,
      boron: 0.25,
      cec: 12,
      baseSaturation: 63,
    },
    labName: "Prairie Analytics",
  },
  {
    name: "alfalfa_low_ph",
    crop: "alfalfa",
    season: "establishment",
    locations: ["Dane County, WI", "Portage County, WI"],
    symptoms: "weak stand establishment and yellowing",
    expectedDiagnosis: "Low pH limiting nutrient availability",
    expectedConditionType: "environmental",
    mustInclude: ["lime recommendation", "target pH", "follow-up test"],
    shouldAvoid: ["high N recommendations"],
    labData: {
      ph: 5.2,
      soilPh: 5.2,
      organicMatter: 3.0,
      nitrogen: 8,
      phosphorus: 9,
      potassium: 95,
      calcium: 620,
      magnesium: 85,
      sulfur: 9,
      zinc: 0.4,
      manganese: 14,
      iron: 28,
      copper: 0.3,
      boron: 0.3,
      cec: 10,
      baseSaturation: 45,
    },
    labName: "Upper Midwest Labs",
  },
  {
    name: "barley_zinc_deficiency",
    crop: "barley",
    season: "tillering",
    locations: ["Ada County, ID", "Minidoka County, ID"],
    symptoms: "striped interveinal chlorosis on young leaves",
    expectedDiagnosis: "Zinc deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["tissue test", "foliar vs soil zinc", "pH context"],
    shouldAvoid: ["misdiagnosing as nitrogen deficiency"],
    labData: {
      ph: 7.7,
      soilPh: 7.7,
      organicMatter: 1.5,
      nitrogen: 9,
      phosphorus: 15,
      potassium: 105,
      calcium: 1700,
      magnesium: 190,
      sulfur: 8,
      zinc: 0.2,
      manganese: 3,
      iron: 12,
      copper: 0.2,
      boron: 0.3,
      cec: 14,
      baseSaturation: 75,
    },
    labName: "Intermountain Labs",
  },
  {
    name: "peanut_calcium_deficiency",
    crop: "peanut",
    season: "pegging",
    locations: ["Tift County, GA", "Coffee County, GA"],
    symptoms: "poor pod fill and empty pods",
    expectedDiagnosis: "Calcium deficiency in pegging zone",
    expectedConditionType: "deficiency",
    mustInclude: ["gypsum recommendation", "pegging zone focus", "timing"],
    shouldAvoid: ["foliar calcium only"],
    labData: {
      ph: 6.0,
      soilPh: 6.0,
      organicMatter: 1.2,
      nitrogen: 8,
      phosphorus: 18,
      potassium: 90,
      calcium: 350,
      magnesium: 70,
      sulfur: 9,
      zinc: 0.5,
      manganese: 6,
      iron: 15,
      copper: 0.2,
      boron: 0.4,
      cec: 6,
      baseSaturation: 50,
    },
    labName: "Southeast Crop Lab",
  },
  {
    name: "potato_manganese_toxicity",
    crop: "potato",
    season: "early bulking",
    locations: ["Antigo, WI", "Central WI"],
    symptoms: "dark speckling and leaf bronzing on acidic soil",
    expectedDiagnosis: "Manganese toxicity due to low pH",
    expectedConditionType: "environmental",
    mustInclude: ["lime recommendation", "pH correction", "monitor Mn"],
    shouldAvoid: ["adding more manganese"],
    labData: {
      ph: 5.0,
      soilPh: 5.0,
      organicMatter: 2.8,
      nitrogen: 11,
      phosphorus: 14,
      potassium: 115,
      calcium: 520,
      magnesium: 75,
      sulfur: 10,
      zinc: 0.7,
      manganese: 28,
      iron: 30,
      copper: 0.4,
      boron: 0.3,
      cec: 9,
      baseSaturation: 42,
    },
    labName: "Great Lakes Soil Lab",
  },
  {
    name: "wheat_low_phosphorus",
    crop: "wheat",
    season: "jointing",
    locations: ["Morrow County, OR", "Whitman County, WA"],
    symptoms: "stunted growth and purpling of older leaves",
    expectedDiagnosis: "Phosphorus deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["placement strategy", "soil test confirmation", "starter timing"],
    shouldAvoid: ["blanket high-rate phosphorus"],
    labData: {
      ph: 6.0,
      soilPh: 6.0,
      organicMatter: 1.4,
      nitrogen: 12,
      phosphorus: 6,
      potassium: 80,
      calcium: 900,
      magnesium: 110,
      sulfur: 7,
      zinc: 0.5,
      manganese: 5,
      iron: 14,
      copper: 0.3,
      boron: 0.3,
      cec: 8,
      baseSaturation: 55,
    },
    labName: "Pacific Northwest Labs",
  },
  {
    name: "soybean_low_om",
    crop: "soybean",
    season: "V3",
    locations: ["Logan County, NE", "Dawson County, NE"],
    symptoms: "uneven emergence and low vigor on sandy soil",
    expectedDiagnosis: "Low organic matter limiting nutrient supply",
    expectedConditionType: "environmental",
    mustInclude: ["organic matter improvement", "cover crops", "nutrient timing"],
    shouldAvoid: ["overstating quick recovery"],
    labData: {
      ph: 6.6,
      soilPh: 6.6,
      organicMatter: 0.8,
      nitrogen: 6,
      phosphorus: 10,
      potassium: 70,
      calcium: 700,
      magnesium: 90,
      sulfur: 6,
      zinc: 0.4,
      manganese: 4,
      iron: 12,
      copper: 0.2,
      boron: 0.2,
      cec: 5,
      baseSaturation: 50,
    },
    labName: "Great Plains Labs",
  },
  {
    name: "corn_high_ph_low_mn",
    crop: "corn",
    season: "V5",
    locations: ["Fresno County, CA", "Kings County, CA"],
    symptoms: "interveinal chlorosis on young leaves on high pH soil",
    expectedDiagnosis: "Manganese deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["tissue test", "foliar manganese", "pH context"],
    shouldAvoid: ["ignoring pH limitation"],
    labData: {
      ph: 7.9,
      soilPh: 7.9,
      organicMatter: 1.2,
      nitrogen: 10,
      phosphorus: 15,
      potassium: 120,
      calcium: 1900,
      magnesium: 210,
      sulfur: 9,
      zinc: 0.5,
      manganese: 2,
      iron: 10,
      copper: 0.2,
      boron: 0.3,
      cec: 12,
      baseSaturation: 80,
    },
    labName: "Central Valley Soil Lab",
  },
  {
    name: "rice_zinc_deficiency",
    crop: "rice",
    season: "tillering",
    locations: ["Stuttgart, AR", "Crowley, LA"],
    symptoms: "bronzing leaves and stunted tillers",
    expectedDiagnosis: "Zinc deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["zinc source", "flooding management", "tissue test"],
    shouldAvoid: ["late season rescue"],
    labData: {
      ph: 6.8,
      soilPh: 6.8,
      organicMatter: 2.4,
      nitrogen: 9,
      phosphorus: 12,
      potassium: 95,
      calcium: 900,
      magnesium: 120,
      sulfur: 8,
      zinc: 0.2,
      manganese: 6,
      iron: 15,
      copper: 0.3,
      boron: 0.3,
      cec: 9,
      baseSaturation: 60,
    },
    labName: "Delta Ag Lab",
  },
  {
    name: "alfalfa_k_deficiency",
    crop: "alfalfa",
    season: "mid-season",
    locations: ["Kearney County, NE", "Lancaster County, NE"],
    symptoms: "leaf edge scorch and reduced regrowth after cutting",
    expectedDiagnosis: "Potassium deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["split K application", "tissue test", "water management"],
    shouldAvoid: ["single high-rate KCl in drought"],
    labData: {
      ph: 6.5,
      soilPh: 6.5,
      organicMatter: 2.6,
      nitrogen: 10,
      phosphorus: 14,
      potassium: 55,
      calcium: 1100,
      magnesium: 160,
      sulfur: 9,
      zinc: 0.6,
      manganese: 7,
      iron: 18,
      copper: 0.3,
      boron: 0.5,
      cec: 16,
      baseSaturation: 65,
    },
    labName: "Plains Ag Lab",
  },
  {
    name: "corn_high_k_low_mg",
    crop: "corn",
    season: "V6",
    locations: ["Shelby County, TN", "Madison County, TN"],
    symptoms: "interveinal chlorosis on lower leaves with brittle tissue",
    expectedDiagnosis: "Magnesium deficiency due to high K",
    expectedConditionType: "deficiency",
    mustInclude: ["check K:Mg balance", "magnesium source", "rate guardrails"],
    shouldAvoid: ["more potassium"],
    labData: {
      ph: 6.4,
      soilPh: 6.4,
      organicMatter: 2.0,
      nitrogen: 11,
      phosphorus: 17,
      potassium: 210,
      calcium: 900,
      magnesium: 55,
      sulfur: 10,
      zinc: 0.6,
      manganese: 8,
      iron: 19,
      copper: 0.3,
      boron: 0.4,
      cec: 12,
      baseSaturation: 60,
    },
    labName: "Mid-South Labs",
  },
  {
    name: "cotton_low_k",
    crop: "cotton",
    season: "flowering",
    locations: ["Pinal County, AZ", "Yuma County, AZ"],
    symptoms: "leaf edge scorching and poor boll retention",
    expectedDiagnosis: "Potassium deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["split K application", "petiole test", "water management"],
    shouldAvoid: ["single large K burst in drought"],
    labData: {
      ph: 7.4,
      soilPh: 7.4,
      organicMatter: 1.1,
      nitrogen: 9,
      phosphorus: 12,
      potassium: 60,
      calcium: 1450,
      magnesium: 180,
      sulfur: 7,
      zinc: 0.4,
      manganese: 4,
      iron: 12,
      copper: 0.2,
      boron: 0.3,
      cec: 10,
      baseSaturation: 70,
    },
    labName: "Desert Crop Lab",
  },
  {
    name: "sugarbeet_boron_def",
    crop: "sugarbeet",
    season: "mid-season",
    locations: ["Red River Valley, MN", "Pembina County, ND"],
    symptoms: "black heart and distorted new growth",
    expectedDiagnosis: "Boron deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["boron tissue test", "rate guardrails", "avoid toxicity"],
    shouldAvoid: ["excess boron application"],
    labData: {
      ph: 7.2,
      soilPh: 7.2,
      organicMatter: 3.2,
      nitrogen: 12,
      phosphorus: 16,
      potassium: 140,
      calcium: 1400,
      magnesium: 200,
      sulfur: 11,
      zinc: 0.5,
      manganese: 6,
      iron: 15,
      copper: 0.3,
      boron: 0.2,
      cec: 18,
      baseSaturation: 72,
    },
    labName: "Northern Plains Labs",
  },
  {
    name: "wheat_high_ph_low_zn",
    crop: "wheat",
    season: "tillering",
    locations: ["Cimarron County, OK", "Texas County, OK"],
    symptoms: "stunted plants with pale stripes on young leaves",
    expectedDiagnosis: "Zinc deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["zinc source", "placement strategy", "tissue test"],
    shouldAvoid: ["ignoring pH interaction"],
    labData: {
      ph: 7.6,
      soilPh: 7.6,
      organicMatter: 1.4,
      nitrogen: 10,
      phosphorus: 24,
      potassium: 95,
      calcium: 1600,
      magnesium: 190,
      sulfur: 8,
      zinc: 0.25,
      manganese: 4,
      iron: 13,
      copper: 0.2,
      boron: 0.3,
      cec: 12,
      baseSaturation: 75,
    },
    labName: "Southern Plains Labs",
  },
  {
    name: "corn_high_salinity_proxy",
    crop: "corn",
    season: "V3",
    locations: ["Imperial County, CA", "Yuma County, AZ"],
    symptoms: "leaf tip burn and uneven emergence on saline patches",
    expectedDiagnosis: "Salinity stress",
    expectedConditionType: "environmental",
    mustInclude: ["irrigation management", "leaching strategy", "monitor EC"],
    shouldAvoid: ["overapplying fertilizer"],
    labData: {
      ph: 7.9,
      soilPh: 7.9,
      organicMatter: 0.9,
      nitrogen: 9,
      phosphorus: 14,
      potassium: 130,
      calcium: 1800,
      magnesium: 220,
      sulfur: 12,
      zinc: 0.5,
      manganese: 3,
      iron: 10,
      copper: 0.2,
      boron: 0.4,
      cec: 10,
      baseSaturation: 78,
    },
    labName: "Desert Crop Lab",
  },
  {
    name: "soybean_low_p",
    crop: "soybean",
    season: "V2",
    locations: ["Cass County, MO", "Pike County, MO"],
    symptoms: "stunted growth and dark green leaves",
    expectedDiagnosis: "Phosphorus deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["soil test confirmation", "placement strategy", "pH correction"],
    shouldAvoid: ["blanket high-rate phosphorus"],
    labData: {
      ph: 5.8,
      soilPh: 5.8,
      organicMatter: 2.0,
      nitrogen: 11,
      phosphorus: 7,
      potassium: 100,
      calcium: 820,
      magnesium: 120,
      sulfur: 8,
      zinc: 0.5,
      manganese: 8,
      iron: 18,
      copper: 0.3,
      boron: 0.3,
      cec: 10,
      baseSaturation: 55,
    },
    labName: "Ozark Soil Lab",
  },
  {
    name: "corn_low_ca",
    crop: "corn",
    season: "V6",
    locations: ["Polk County, FL", "DeSoto County, FL"],
    symptoms: "weak root development and uneven stand on sandy soil",
    expectedDiagnosis: "Low calcium due to low CEC",
    expectedConditionType: "deficiency",
    mustInclude: ["calcium source", "CEC context", "split applications"],
    shouldAvoid: ["overapplying potassium"],
    labData: {
      ph: 5.9,
      soilPh: 5.9,
      organicMatter: 0.7,
      nitrogen: 8,
      phosphorus: 12,
      potassium: 70,
      calcium: 300,
      magnesium: 55,
      sulfur: 6,
      zinc: 0.4,
      manganese: 7,
      iron: 12,
      copper: 0.2,
      boron: 0.2,
      cec: 4,
      baseSaturation: 40,
    },
    labName: "Southeast Soil Lab",
  },
  {
    name: "alfalfa_high_k_low_mg",
    crop: "alfalfa",
    season: "mid-season",
    locations: ["Jefferson County, WI", "Grant County, WI"],
    symptoms: "interveinal chlorosis and brittle leaves",
    expectedDiagnosis: "Magnesium deficiency due to high K",
    expectedConditionType: "deficiency",
    mustInclude: ["check K:Mg balance", "magnesium source", "rate guardrails"],
    shouldAvoid: ["add more potassium"],
    labData: {
      ph: 6.7,
      soilPh: 6.7,
      organicMatter: 3.2,
      nitrogen: 11,
      phosphorus: 16,
      potassium: 230,
      calcium: 1200,
      magnesium: 60,
      sulfur: 10,
      zinc: 0.7,
      manganese: 8,
      iron: 20,
      copper: 0.3,
      boron: 0.5,
      cec: 18,
      baseSaturation: 70,
    },
    labName: "Upper Midwest Labs",
  },
  {
    name: "tomato_low_k",
    crop: "tomato",
    season: "early fruit set",
    locations: ["Dade County, FL", "Collier County, FL"],
    symptoms: "leaf edge scorch and uneven ripening",
    expectedDiagnosis: "Potassium deficiency",
    expectedConditionType: "deficiency",
    mustInclude: ["rate by soil test", "split applications", "irrigation timing"],
    shouldAvoid: ["single large K dose"],
    labData: {
      ph: 6.1,
      soilPh: 6.1,
      organicMatter: 1.3,
      nitrogen: 10,
      phosphorus: 14,
      potassium: 65,
      calcium: 850,
      magnesium: 120,
      sulfur: 9,
      zinc: 0.5,
      manganese: 6,
      iron: 14,
      copper: 0.2,
      boron: 0.3,
      cec: 8,
      baseSaturation: 58,
    },
    labName: "Vegetable Analytics",
  },
];
